name: melostestworkspace

publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

workspace:
  - app
  - design_system
  - design_system_assets
  - shared
  - modules/mfa
  - modules/notifications
  - modules/showcases
  - modules/user

dev_dependencies:
  melos: ^6.2.0